#!/usr/bin/env node
/*
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

/*
 * Regenerates src/api/bedrock-prompts.js from the editable prompt sources in
 * src/api/prompts/*.md. Run `npm run build:prompts` after editing a prompt.
 *
 * Why generate instead of importing the .md at runtime: the Lambda is bundled
 * by hedy/esbuild with no .md loader configured, so a committed generated
 * module is the reliable way to ship the prompts inside the bundle.
 */
import { readFileSync, writeFileSync } from 'fs';
import path from 'path';

const ROOT = process.cwd();
const PROMPTS = path.join(ROOT, 'src', 'api', 'prompts');
const OUT = path.join(ROOT, 'src', 'api', 'bedrock-prompts.js');

const read = (f) => readFileSync(path.join(PROMPTS, f), 'utf8');
// Escape only what a template literal requires; real newlines stay as newlines.
const tmpl = (s) => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

const systemPrompt = read('system-prompt.md');
const overviewTemplate = read('overview-analysis-template.md');

const out = `/*
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

/*
 * DO NOT EDIT THIS FILE. It is generated by tools/build-prompts.mjs from the
 * prompt sources in src/api/prompts/*.md. Edit those .md files and run
 * \`npm run build:prompts\` to regenerate. The prompts live in .md so they are
 * readable/editable outside JS; they are inlined here so hedy/esbuild bundles
 * them into the Lambda.
 */

/* eslint-disable */

export const SYSTEM_PROMPT = \`${tmpl(systemPrompt)}\`;

export const OVERVIEW_TEMPLATE = \`${tmpl(overviewTemplate)}\`;
`;

writeFileSync(OUT, out);
// eslint-disable-next-line no-console
console.log(`bedrock-prompts.js regenerated (${systemPrompt.length} + ${overviewTemplate.length} chars)`);
